### ISSUE TITLE
welp app chrash 

### ISSUE THREAD

**Issue by daklehmar** [micah686/Visual-Novel-Manager#2]
The app crash when i try to log with my vndb account
here is the result of the debug log

checking username and password
Attempting to get a user's Vn list
retrieving user's vns from apid
retrieving user's vote's api
create list of IDs from sql
get basic info from list of VNsget basic info from list of VNs
get list of items from sql db, or from api if missing
get all items from sql db vnlistget all items from db vnlist
get ids NOT in sql database
get details
add items to list to bind
EXCEPTION OCCURED:

La référence d'objet n'est pas définie à une instance d'un objet.
   à VisualNovelManager.ViewModel.UserVnListViewModel.<GetVnName>d__43.MoveNext()
Void MoveNext()EXCEPTION OCCURED:
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à VisualNovelManager.ViewModel.UserVnListViewModel.<GetVnName>d__43.MoveNext()
Une ou plusieurs erreurs se sont produites.
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   à System.Threading.Tasks.Task`1.get_Result()
   à VisualNovelManager.ViewModel.UserVnListViewModel.<GetVnListVoteList>d__42.MoveNext()
Void ThrowIfExceptional(Boolean)EXCEPTION OCCURED:
System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à VisualNovelManager.ViewModel.UserVnListViewModel.<GetVnName>d__43.MoveNext()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   à System.Threading.Tasks.Task`1.get_Result()
   à VisualNovelManager.ViewModel.UserVnListViewModel.<GetVnListVoteList>d__42.MoveNext()
---> (Exception interne #0) System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à VisualNovelManager.ViewModel.UserVnListViewModel.<GetVnName>d__43.MoveNext()<---

Une ou plusieurs erreurs se sont produites.
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   à System.Threading.Tasks.Task`1.get_Result()
   à VisualNovelManager.ViewModel.UserVnListViewModel.<>c__DisplayClass33_0.<GetUserVnListExecute>b__2()
   à System.Threading.Tasks.Task.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à VisualNovelManager.ViewModel.UserVnListViewModel.<GetUserVnListExecute>d__33.MoveNext()
Void ThrowIfExceptional(Boolean)

**Comment by micah686** [comment]
I'm trying to rework the program to fix a lot of the issues and crashing, under the 'develop' branch. I'll see about trying to get the VnList fixed next.

**Comment by micah686** [comment]
Closed due to age, and the fact that I will no longer be working on this code.
