### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by shukumeiteki** [micah686/Visual-Novel-Manager#5]
Here is the error I'm having since 1.0 ver, every time I try to log in this happens and when I do (1 out of 10) it also crashes when I try to execute a VN or just select some of them.

[debug.txt](https://github.com/micah686/Visual-Novel-Manager/files/428202/debug.txt)
[debug2.txt](https://github.com/micah686/Visual-Novel-Manager/files/428204/debug2.txt)

**Comment by micah686** [comment]
Closed due to age, and the fact that I will no longer be working on this code.
